spring.application.name=homework
server.port=9091
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/movie
spring.datasource.username=b
spring.datasource.password=
spring.jpa.show-sql=true
